name: Performance Test

on: push

jobs:
  super-lint:
    name: Performance Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Run performance testing script
        run: ./reassure-tests.sh

      - name: Run Danger.js
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}